name: Prettier

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
      - run: corepack enable
      - run: yarn install
      - name: Run Prettier
        run: |
          yarn format:check
