name: Build and Package on Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: tgfoa-bepinex

      - name: Upload release asset
        uses: softprops/action-gh-release@v3
        with:
          files: tgfoa-bepinex.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
